version: "3.8"

services:
  backend:
    build: ./backend
    container_name: weight-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    networks:
      - weight-network

  frontend:
    build: ./frontend
    container_name: weight-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - weight-network

networks:
  weight-network:
    driver: bridge
