/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 07 21:05:25 GMT 2025
 */
/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.commons.collections4.bag;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Collection;
import org.apache.commons.collections4.bag.HashBag;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class HashBag_ESTest extends HashBag_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HashBag<Boolean> hashBag0 = null;
      try {
        hashBag0 = new HashBag<Boolean>((Collection<? extends Boolean>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.collections4.bag.AbstractMapBag", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      HashBag<Object> hashBag0 = null;
      try {
        hashBag0 = new HashBag<Object>((Iterable<?>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.collections4.bag.AbstractMapBag", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      HashBag<Integer> hashBag0 = new HashBag<Integer>();
      HashBag<Integer> hashBag1 = new HashBag<Integer>((Iterable<? extends Integer>) hashBag0);
      assertTrue(hashBag1.isEmpty());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      HashBag<Integer> hashBag0 = new HashBag<Integer>();
      HashBag<Object> hashBag1 = new HashBag<Object>((Collection<?>) hashBag0);
      assertEquals(0, hashBag1.size());
  }
}
